/* groovylint-disable-next-line CompileStatic */
pipeline {
    agent any

    stages {

        stage('Clean Up') {
            steps {
                deleteDir()
            }
        }

        stage('Build') {
            steps {
                dir('JAVA-MAVEN') {
                    bat 'mvn clean package'
                }
            }
        }

        stage('Deploy') {
            steps {
                input 'Deploy to local directory?'
                echo 'Deploying...'
                bat 'xcopy /Y /I target\\*.jar C:\\MYBUILDS\\'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
        }
    }
}