/* groovylint-disable-next-line CompileStatic */
pipeline {
    agent any

    stages {

        stage('Clean Up') {
            steps {
                deleteDir()
            }
        }

        stage('Clone Repo') {
            steps {
                // Cloning the repository is not necessary here if using "Pipeline script from SCM"
                // Remove this stage if it's redundant
                // bat 'git clone https://github.com/AbhilashSivaraman/JAVA-MAVEN.git'
            }
        }

        stage('Build') {
            steps {
                // Build the Java application using Maven
                dir('JAVA-MAVEN') {
                    bat 'mvn clean package'
                }
            }
        }

        stage('Deploy') {
            steps {
                input 'Deploy to local directory?'
                echo 'Deploying...'
                // Copy the built JAR file to a local directory
                bat 'xcopy /Y /I target\\*.jar C:\\MYBUILDS\\'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
        }
    }
}
